name: student_login_quik
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animate_do: ^2.1.0
  animated_text_kit: ^4.2.2
  circular_profile_avatar: ^2.0.5
  cloud_firestore: ^3.5.0
  cross_file_image: ^1.0.0
  cupertino_icons: ^1.0.2
  date_format: null
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  path_provider: null

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/5.jpeg
    - assets/images/6.jpeg
    - assets/images/7.jpeg
    - assets/images/8.jpeg
    - assets/images/9.jpeg
    - assets/images/10.jpeg
    - assets/images/11.jpeg
    - assets/images/12.jpeg
    - assets/images/13.jpeg
    - assets/images/14.jpeg
    - assets/images/15.jpeg
    - assets/images/35.jpeg
    - assets/images/17.jpeg
    - assets/images/18.jpeg
    - assets/images/19.jpeg
    - assets/images/20.jpeg
    - assets/images/21.jpeg
    - assets/images/22.jpeg
    - assets/images/23.jpeg
    - assets/images/24.jpeg
    - assets/images/25.jpeg
    - assets/images/26.jpeg
    - assets/images/27.jpeg
    - assets/images/28.jpeg
    - assets/images/29.jpeg
    - assets/images/30.jpeg
    - assets/images/31.jpeg
    - assets/images/32.jpeg
    - assets/images/33.jpeg
    - assets/images/34.jpeg
    - assets/istockphoto-1018999828-612x612.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
